
import json
import logging
import os
from datetime import datetime
from typing import Any, Dict, List

import requests
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


JIRA_BASE_URL = os.getenv("JIRA_BASE_URL")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN")
JIRA_EMAIL = os.getenv("JIRA_EMAIL")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY")
JIRA_ISSUE_TYPE = os.getenv("JIRA_ISSUE_TYPE", "Story")
JIRA_STORY_POINTS_FIELD = os.getenv("JIRA_STORY_POINTS_FIELD", "customfield_10016")

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")
SLACK_CHANNEL = os.getenv("SLACK_CHANNEL", "#product-updates")


def _is_jira_configured() -> bool:
    return all([JIRA_BASE_URL, JIRA_API_TOKEN, JIRA_EMAIL, JIRA_PROJECT_KEY])


def _is_slack_configured() -> bool:
    return bool(SLACK_WEBHOOK_URL)


class MockJiraClient:

    def __init__(self):
        self.stories: List[Dict[str, Any]] = []
        self.story_id_counter = 1000

    def create_story(self, title: str, description: str, story_points: int) -> Dict[str, Any]:
        story = {
            "id": f"PROJ-{self.story_id_counter}",
            "title": title,
            "description": description,
            "story_points": story_points,
            "status": "To Do",
            "created_at": datetime.now().isoformat(),
            "url": f"https://jira.example.com/browse/PROJ-{self.story_id_counter}",
        }
        self.stories.append(story)
        self.story_id_counter += 1
        return story

    def bulk_create_stories(self, user_stories: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        return [
            self.create_story(
                title=story.get("title", "Untitled Story"),
                description=story.get("description", ""),
                story_points=int(story.get("story_points", 3)),
            )
            for story in user_stories
        ]


class RealJiraClient:

    def __init__(self):
        if not _is_jira_configured():
            raise ValueError("Jira environment variables are not fully configured.")
        self.base_url = JIRA_BASE_URL.rstrip("/")
        self.auth = (JIRA_EMAIL, JIRA_API_TOKEN)
        self.headers = {"Accept": "application/json", "Content-Type": "application/json"}
        self.story_points_field = JIRA_STORY_POINTS_FIELD.strip() if JIRA_STORY_POINTS_FIELD else ""

    def _build_payload(self, title: str, description: str, story_points: int) -> Dict[str, Any]:
        fields: Dict[str, Any] = {
            "project": {"key": JIRA_PROJECT_KEY},
            "summary": title[:240] or "Untitled Story",
            "description": self._format_description(description),
            "issuetype": {"name": JIRA_ISSUE_TYPE},
        }
        if story_points is not None and self.story_points_field:
            fields[self.story_points_field] = story_points
        return {"fields": fields}

    def _post_issue(self, payload: Dict[str, Any]) -> requests.Response:
        return requests.post(
            f"{self.base_url}/rest/api/3/issue",
            headers=self.headers,
            auth=self.auth,
            json=payload,
            timeout=30,
        )

    @staticmethod
    def _format_description(text: str) -> Dict[str, Any]:
        """plain txt ---> (ADF)."""
        cleaned = (text or "").strip()
        if not cleaned:
            cleaned = "Generated by Genvis"
        paragraphs = []
        for line in cleaned.split("\n"):
            line = line.strip()
            if not line:
                paragraphs.append({"type": "paragraph"})
                continue
            paragraphs.append(
                {"type": "paragraph", "content": [{"type": "text", "text": line[:1000]}]}
            )
        return {"type": "doc", "version": 1, "content": paragraphs or [{"type": "paragraph"}]}

    def create_story(self, title: str, description: str, story_points: int) -> Dict[str, Any]:
        payload = self._build_payload(title, description, story_points)
        response = self._post_issue(payload)


        if (
            response.status_code == 400
            and self.story_points_field
            and self.story_points_field in response.text
        ):
            logger.warning(
                "Jira rejected story points field '%s'. Retrying without story points.",
                self.story_points_field,
            )
            payload = self._build_payload(title, description, None)
            response = self._post_issue(payload)

        if not response.ok:
            logger.error("Jira API error %s: %s", response.status_code, response.text)
            raise RuntimeError(f"Jira API error {response.status_code}: {response.text}")

        data = response.json()
        issue_key = data.get("key")
        return {
            "id": issue_key,
            "title": title,
            "story_points": story_points,
            "url": f"{self.base_url}/browse/{issue_key}" if issue_key else None,
        }

    def bulk_create_stories(self, user_stories: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        created = []
        for story in user_stories:
            created.append(
                self.create_story(
                    title=story.get("title", "Untitled Story"),
                    description=story.get("description", ""),
                    story_points=int(story.get("story_points", 3)),
                )
            )
        return created


class MockSlackClient:

    def __init__(self):
        self.messages: List[Dict[str, Any]] = []

    def send_sprint_summary(self, sprint_report: Dict[str, Any]) -> Dict[str, Any]:
        message = {
            "channel": SLACK_CHANNEL,
            "text": sprint_report.get("executive_summary", "Sprint summary"),
            "payload": sprint_report,
            "timestamp": datetime.now().isoformat(),
            "status": "sent",
        }
        self.messages.append(message)
        return {"ok": True, "ts": message["timestamp"]}


class RealSlackClient:


    def __init__(self):
        if not _is_slack_configured():
            raise ValueError("Slack webhook URL is not configured.")
        self.webhook_url = SLACK_WEBHOOK_URL

    def send_sprint_summary(self, sprint_report: Dict[str, Any]) -> Dict[str, Any]:
        blocks = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": sprint_report.get("sprint_name", "Sprint Update")},
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Executive Summary*\n{ sprint_report.get('executive_summary', 'n/a') }",
                },
            },
        ]
        achievements = sprint_report.get("achievements") or []
        if achievements:
            blocks.append(
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": "*Achievements:*\n• " + "\n• ".join(achievements[:5])},
                }
            )

        payload = {"channel": SLACK_CHANNEL, "text": "Sprint summary available", "blocks": blocks}
        response = requests.post(self.webhook_url, json=payload, timeout=15)
        if not response.ok:
            raise RuntimeError(f"Slack webhook error {response.status_code}: {response.text}")
        return {"ok": True, "status": "sent"}


_jira_client = None
_slack_client = None


def get_jira_client():
    global _jira_client
    if _jira_client is None:
        if _is_jira_configured():
            try:
                _jira_client = RealJiraClient()
                logger.info("Using real Jira client.")
            except Exception as exc:
                logger.error("Failed to init Jira client (%s). Falling back to mock.", exc)
                _jira_client = MockJiraClient()
        else:
            logger.info("Jira env vars not set; using mock Jira client.")
            _jira_client = MockJiraClient()
    return _jira_client


def get_slack_client():
    global _slack_client
    if _slack_client is None:
        if _is_slack_configured():
            try:
                _slack_client = RealSlackClient()
                logger.info("Using real Slack client.")
            except Exception as exc:
                logger.error("Failed to init Slack client (%s). Falling back to mock.", exc)
                _slack_client = MockSlackClient()
        else:
            logger.info("Slack webhook not set; using mock Slack client.")
            _slack_client = MockSlackClient()
    return _slack_client
